name: air_vision
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sensors: ^0.4.1+10
  camera: ^0.5.7+4
  shared_preferences: ^0.5.7+1
  
  location: ^2.5.0
  google_maps_flutter: ^0.5.24+1
  connectivity: ^0.4.8+6

  tflite: ^1.0.5

  http: ^0.12.0+4
  permission_handler: ^5.0.0+hotfix.2
  app_settings: 4.0.0

  vector_math: ^2.0.8

  flutter_spinkit: "^4.1.2"
  fluttertoast: ^4.0.1

  toggle_switch: "^0.1.4"
  bottom_navy_bar: ^5.3.2
  font_awesome_flutter: ^8.7.0
  line_icons: ^0.2.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
