name: air_vision
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  camera: ^0.5.7+4
  location: ^2.5.0
  sensors: ^0.4.1+10
  font_awesome_flutter: ^8.7.0
  google_maps_flutter: ^0.5.24+1
  provider: ^4.0.4
  tflite: ^1.0.5
  http: ^0.12.0+4
  basic_utils: ^2.5.3
  flutter_spinkit: "^4.1.2"
  fluttertoast: ^4.0.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
